name: Translate Readme

on:
  push:
    branches:
      - main
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Adding License
        uses: dephraiim/translate-readme@v1
        with:
          LANG: es
          # ISO Langusge Code.
          # Supported Languages below

      - name: Translate Readme Action
        # You may pin to the exact commit or the version.
        # uses: dephraiim/translate-readme@e880ba3fc519efeab0368619207604003e7049f8
        uses: dephraiim/translate-readme@v1
        with:
          # The Language you want to translate to
          LANG: es
